#!/bin/tcsh

set theta = 90
set posang = 0
foreach phi (`nums -90 0 -ns 10 -np 0`)
radmc3d image lambda 0.4e3 theta $theta phi $phi nostar posang $posang pointpc 0.5 0.5 0.5  npix 256 sizepc 1
mv image.out image_z_"$theta"_"$phi".out
end

python problem_plot.py
#end
